//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsmxService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Funcionario", Namespace="http://tempuri.org/")]
    public partial class Funcionario : object
    {
        
        private int IdField;
        
        private string NomeField;
        
        private int NIFField;
        
        private System.DateTime DataEntradaField;
        
        private int ContactoField;
        
        private string PasswordField;
        
        private int TipoFuncionárioidField;
        
        private string JWTField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int NIF
        {
            get
            {
                return this.NIFField;
            }
            set
            {
                this.NIFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DataEntrada
        {
            get
            {
                return this.DataEntradaField;
            }
            set
            {
                this.DataEntradaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Contacto
        {
            get
            {
                return this.ContactoField;
            }
            set
            {
                this.ContactoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int TipoFuncionárioid
        {
            get
            {
                return this.TipoFuncionárioidField;
            }
            set
            {
                this.TipoFuncionárioidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string JWT
        {
            get
            {
                return this.JWTField;
            }
            set
            {
                this.JWTField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AsmxService.HospitalServiceSoap")]
    public interface HospitalServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllFuncionarios", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxService.GetAllFuncionariosResponse> GetAllFuncionariosAsync(AsmxService.GetAllFuncionariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFuncionarioById", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxService.GetFuncionarioByIdResponse> GetFuncionarioByIdAsync(AsmxService.GetFuncionarioByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateFuncionario", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxService.CreateFuncionarioResponse> CreateFuncionarioAsync(AsmxService.CreateFuncionarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateFuncionario", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxService.UpdateFuncionarioResponse> UpdateFuncionarioAsync(AsmxService.UpdateFuncionarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFuncionario", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteFuncionarioAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllFuncionariosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllFuncionarios", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.GetAllFuncionariosRequestBody Body;
        
        public GetAllFuncionariosRequest()
        {
        }
        
        public GetAllFuncionariosRequest(AsmxService.GetAllFuncionariosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllFuncionariosRequestBody
    {
        
        public GetAllFuncionariosRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllFuncionariosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllFuncionariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.GetAllFuncionariosResponseBody Body;
        
        public GetAllFuncionariosResponse()
        {
        }
        
        public GetAllFuncionariosResponse(AsmxService.GetAllFuncionariosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllFuncionariosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AsmxService.Funcionario[] GetAllFuncionariosResult;
        
        public GetAllFuncionariosResponseBody()
        {
        }
        
        public GetAllFuncionariosResponseBody(AsmxService.Funcionario[] GetAllFuncionariosResult)
        {
            this.GetAllFuncionariosResult = GetAllFuncionariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFuncionarioByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFuncionarioById", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.GetFuncionarioByIdRequestBody Body;
        
        public GetFuncionarioByIdRequest()
        {
        }
        
        public GetFuncionarioByIdRequest(AsmxService.GetFuncionarioByIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFuncionarioByIdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetFuncionarioByIdRequestBody()
        {
        }
        
        public GetFuncionarioByIdRequestBody(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFuncionarioByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFuncionarioByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.GetFuncionarioByIdResponseBody Body;
        
        public GetFuncionarioByIdResponse()
        {
        }
        
        public GetFuncionarioByIdResponse(AsmxService.GetFuncionarioByIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFuncionarioByIdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AsmxService.Funcionario GetFuncionarioByIdResult;
        
        public GetFuncionarioByIdResponseBody()
        {
        }
        
        public GetFuncionarioByIdResponseBody(AsmxService.Funcionario GetFuncionarioByIdResult)
        {
            this.GetFuncionarioByIdResult = GetFuncionarioByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateFuncionarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateFuncionario", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.CreateFuncionarioRequestBody Body;
        
        public CreateFuncionarioRequest()
        {
        }
        
        public CreateFuncionarioRequest(AsmxService.CreateFuncionarioRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateFuncionarioRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int nif;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime dataEntrada;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int contacto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int tipoFuncionarioId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string jwt;
        
        public CreateFuncionarioRequestBody()
        {
        }
        
        public CreateFuncionarioRequestBody(string nome, int nif, System.DateTime dataEntrada, int contacto, string password, int tipoFuncionarioId, string jwt)
        {
            this.nome = nome;
            this.nif = nif;
            this.dataEntrada = dataEntrada;
            this.contacto = contacto;
            this.password = password;
            this.tipoFuncionarioId = tipoFuncionarioId;
            this.jwt = jwt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateFuncionarioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateFuncionarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.CreateFuncionarioResponseBody Body;
        
        public CreateFuncionarioResponse()
        {
        }
        
        public CreateFuncionarioResponse(AsmxService.CreateFuncionarioResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateFuncionarioResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateFuncionarioResult;
        
        public CreateFuncionarioResponseBody()
        {
        }
        
        public CreateFuncionarioResponseBody(bool CreateFuncionarioResult)
        {
            this.CreateFuncionarioResult = CreateFuncionarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFuncionarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFuncionario", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.UpdateFuncionarioRequestBody Body;
        
        public UpdateFuncionarioRequest()
        {
        }
        
        public UpdateFuncionarioRequest(AsmxService.UpdateFuncionarioRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateFuncionarioRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int nif;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dataEntrada;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int contacto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int tipoFuncionarioId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string jwt;
        
        public UpdateFuncionarioRequestBody()
        {
        }
        
        public UpdateFuncionarioRequestBody(int id, string nome, int nif, System.DateTime dataEntrada, int contacto, string password, int tipoFuncionarioId, string jwt)
        {
            this.id = id;
            this.nome = nome;
            this.nif = nif;
            this.dataEntrada = dataEntrada;
            this.contacto = contacto;
            this.password = password;
            this.tipoFuncionarioId = tipoFuncionarioId;
            this.jwt = jwt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFuncionarioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFuncionarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.UpdateFuncionarioResponseBody Body;
        
        public UpdateFuncionarioResponse()
        {
        }
        
        public UpdateFuncionarioResponse(AsmxService.UpdateFuncionarioResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateFuncionarioResponseBody
    {
        
        public UpdateFuncionarioResponseBody()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface HospitalServiceSoapChannel : AsmxService.HospitalServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class HospitalServiceSoapClient : System.ServiceModel.ClientBase<AsmxService.HospitalServiceSoap>, AsmxService.HospitalServiceSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HospitalServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(HospitalServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), HospitalServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HospitalServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HospitalServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HospitalServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HospitalServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HospitalServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxService.GetAllFuncionariosResponse> AsmxService.HospitalServiceSoap.GetAllFuncionariosAsync(AsmxService.GetAllFuncionariosRequest request)
        {
            return base.Channel.GetAllFuncionariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxService.GetAllFuncionariosResponse> GetAllFuncionariosAsync()
        {
            AsmxService.GetAllFuncionariosRequest inValue = new AsmxService.GetAllFuncionariosRequest();
            inValue.Body = new AsmxService.GetAllFuncionariosRequestBody();
            return ((AsmxService.HospitalServiceSoap)(this)).GetAllFuncionariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxService.GetFuncionarioByIdResponse> AsmxService.HospitalServiceSoap.GetFuncionarioByIdAsync(AsmxService.GetFuncionarioByIdRequest request)
        {
            return base.Channel.GetFuncionarioByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxService.GetFuncionarioByIdResponse> GetFuncionarioByIdAsync(int id)
        {
            AsmxService.GetFuncionarioByIdRequest inValue = new AsmxService.GetFuncionarioByIdRequest();
            inValue.Body = new AsmxService.GetFuncionarioByIdRequestBody();
            inValue.Body.id = id;
            return ((AsmxService.HospitalServiceSoap)(this)).GetFuncionarioByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxService.CreateFuncionarioResponse> AsmxService.HospitalServiceSoap.CreateFuncionarioAsync(AsmxService.CreateFuncionarioRequest request)
        {
            return base.Channel.CreateFuncionarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxService.CreateFuncionarioResponse> CreateFuncionarioAsync(string nome, int nif, System.DateTime dataEntrada, int contacto, string password, int tipoFuncionarioId, string jwt)
        {
            AsmxService.CreateFuncionarioRequest inValue = new AsmxService.CreateFuncionarioRequest();
            inValue.Body = new AsmxService.CreateFuncionarioRequestBody();
            inValue.Body.nome = nome;
            inValue.Body.nif = nif;
            inValue.Body.dataEntrada = dataEntrada;
            inValue.Body.contacto = contacto;
            inValue.Body.password = password;
            inValue.Body.tipoFuncionarioId = tipoFuncionarioId;
            inValue.Body.jwt = jwt;
            return ((AsmxService.HospitalServiceSoap)(this)).CreateFuncionarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxService.UpdateFuncionarioResponse> AsmxService.HospitalServiceSoap.UpdateFuncionarioAsync(AsmxService.UpdateFuncionarioRequest request)
        {
            return base.Channel.UpdateFuncionarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxService.UpdateFuncionarioResponse> UpdateFuncionarioAsync(int id, string nome, int nif, System.DateTime dataEntrada, int contacto, string password, int tipoFuncionarioId, string jwt)
        {
            AsmxService.UpdateFuncionarioRequest inValue = new AsmxService.UpdateFuncionarioRequest();
            inValue.Body = new AsmxService.UpdateFuncionarioRequestBody();
            inValue.Body.id = id;
            inValue.Body.nome = nome;
            inValue.Body.nif = nif;
            inValue.Body.dataEntrada = dataEntrada;
            inValue.Body.contacto = contacto;
            inValue.Body.password = password;
            inValue.Body.tipoFuncionarioId = tipoFuncionarioId;
            inValue.Body.jwt = jwt;
            return ((AsmxService.HospitalServiceSoap)(this)).UpdateFuncionarioAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteFuncionarioAsync(int id)
        {
            return base.Channel.DeleteFuncionarioAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HospitalServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HospitalServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HospitalServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44347/Services/HospitalService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.HospitalServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44347/Services/HospitalService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HospitalServiceSoap,
            
            HospitalServiceSoap12,
        }
    }
}
