//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsmxService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Funcionario", Namespace="http://tempuri.org/")]
    public partial class Funcionario : object
    {
        
        private int IdField;
        
        private string NomeField;
        
        private int NIFField;
        
        private System.DateTime DataEntradaField;
        
        private int ContactoField;
        
        private string PasswordField;
        
        private int TipoFuncionárioidField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int NIF
        {
            get
            {
                return this.NIFField;
            }
            set
            {
                this.NIFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DataEntrada
        {
            get
            {
                return this.DataEntradaField;
            }
            set
            {
                this.DataEntradaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Contacto
        {
            get
            {
                return this.ContactoField;
            }
            set
            {
                this.ContactoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int TipoFuncionárioid
        {
            get
            {
                return this.TipoFuncionárioidField;
            }
            set
            {
                this.TipoFuncionárioidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Utente", Namespace="http://tempuri.org/")]
    public partial class Utente : object
    {
        
        private int IdField;
        
        private string NomeField;
        
        private int NIFField;
        
        private System.DateTime DataEntradaField;
        
        private int TipoUtenteIdField;
        
        private int HospitalIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int NIF
        {
            get
            {
                return this.NIFField;
            }
            set
            {
                this.NIFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DataEntrada
        {
            get
            {
                return this.DataEntradaField;
            }
            set
            {
                this.DataEntradaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int TipoUtenteId
        {
            get
            {
                return this.TipoUtenteIdField;
            }
            set
            {
                this.TipoUtenteIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int HospitalId
        {
            get
            {
                return this.HospitalIdField;
            }
            set
            {
                this.HospitalIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeSpan", Namespace="http://tempuri.org/")]
    public partial class TimeSpan : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Consulta", Namespace="http://tempuri.org/")]
    public partial class Consulta : object
    {
        
        private int IdField;
        
        private int UtenteIdField;
        
        private AsmxService.Utente UtenteField;
        
        private int FuncionárioIdField;
        
        private AsmxService.Funcionario FuncionarioField;
        
        private int HospitalIdField;
        
        private AsmxService.Hospital HospitalField;
        
        private int MedicoIdField;
        
        private AsmxService.Medico MedicoField;
        
        private System.DateTime DataField;
        
        private AsmxService.TimeSpan HoraField;
        
        private string DescricaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UtenteId
        {
            get
            {
                return this.UtenteIdField;
            }
            set
            {
                this.UtenteIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public AsmxService.Utente Utente
        {
            get
            {
                return this.UtenteField;
            }
            set
            {
                this.UtenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int FuncionárioId
        {
            get
            {
                return this.FuncionárioIdField;
            }
            set
            {
                this.FuncionárioIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public AsmxService.Funcionario Funcionario
        {
            get
            {
                return this.FuncionarioField;
            }
            set
            {
                this.FuncionarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int HospitalId
        {
            get
            {
                return this.HospitalIdField;
            }
            set
            {
                this.HospitalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public AsmxService.Hospital Hospital
        {
            get
            {
                return this.HospitalField;
            }
            set
            {
                this.HospitalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int MedicoId
        {
            get
            {
                return this.MedicoIdField;
            }
            set
            {
                this.MedicoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public AsmxService.Medico Medico
        {
            get
            {
                return this.MedicoField;
            }
            set
            {
                this.MedicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=10)]
        public AsmxService.TimeSpan Hora
        {
            get
            {
                return this.HoraField;
            }
            set
            {
                this.HoraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hospital", Namespace="http://tempuri.org/")]
    public partial class Hospital : object
    {
        
        private int IdField;
        
        private string NomeField;
        
        private string LocalizacaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Localizacao
        {
            get
            {
                return this.LocalizacaoField;
            }
            set
            {
                this.LocalizacaoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Medico", Namespace="http://tempuri.org/")]
    public partial class Medico : object
    {
        
        private int IdField;
        
        private string NomeField;
        
        private int TipoMedicoIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TipoMedicoId
        {
            get
            {
                return this.TipoMedicoIdField;
            }
            set
            {
                this.TipoMedicoIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AsmxService.HospitalServiceSoap")]
    public interface HospitalServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllFuncionarios", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxService.GetAllFuncionariosResponse> GetAllFuncionariosAsync(AsmxService.GetAllFuncionariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFuncionarioById", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxService.GetFuncionarioByIdResponse> GetFuncionarioByIdAsync(AsmxService.GetFuncionarioByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateFuncionario", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxService.CreateFuncionarioResponse> CreateFuncionarioAsync(AsmxService.CreateFuncionarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateFuncionario", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxService.UpdateFuncionarioResponse> UpdateFuncionarioAsync(AsmxService.UpdateFuncionarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFuncionario", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteFuncionarioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUtentes", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxService.GetAllUtentesResponse> GetAllUtentesAsync(AsmxService.GetAllUtentesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUtenteById", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxService.GetUtenteByIdResponse> GetUtenteByIdAsync(AsmxService.GetUtenteByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUtente", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxService.CreateUtenteResponse> CreateUtenteAsync(AsmxService.CreateUtenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUtente", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxService.UpdateUtenteResponse> UpdateUtenteAsync(AsmxService.UpdateUtenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUtente", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteUtenteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateConsulta", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxService.CreateConsultaResponse> CreateConsultaAsync(AsmxService.CreateConsultaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllConsultas", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxService.GetAllConsultasResponse> GetAllConsultasAsync(AsmxService.GetAllConsultasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteConsulta", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteConsultaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateConsulta", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxService.UpdateConsultaResponse> UpdateConsultaAsync(AsmxService.UpdateConsultaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaByHospital", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxService.ConsultaByHospitalResponse> ConsultaByHospitalAsync(AsmxService.ConsultaByHospitalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaByUtente", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxService.ConsultaByUtenteResponse> ConsultaByUtenteAsync(AsmxService.ConsultaByUtenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaByFuncionario", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxService.ConsultaByFuncionarioResponse> ConsultaByFuncionarioAsync(AsmxService.ConsultaByFuncionarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaById", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxService.ConsultaByIdResponse> ConsultaByIdAsync(AsmxService.ConsultaByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllFuncionariosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllFuncionarios", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.GetAllFuncionariosRequestBody Body;
        
        public GetAllFuncionariosRequest()
        {
        }
        
        public GetAllFuncionariosRequest(AsmxService.GetAllFuncionariosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllFuncionariosRequestBody
    {
        
        public GetAllFuncionariosRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllFuncionariosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllFuncionariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.GetAllFuncionariosResponseBody Body;
        
        public GetAllFuncionariosResponse()
        {
        }
        
        public GetAllFuncionariosResponse(AsmxService.GetAllFuncionariosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllFuncionariosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AsmxService.Funcionario[] GetAllFuncionariosResult;
        
        public GetAllFuncionariosResponseBody()
        {
        }
        
        public GetAllFuncionariosResponseBody(AsmxService.Funcionario[] GetAllFuncionariosResult)
        {
            this.GetAllFuncionariosResult = GetAllFuncionariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFuncionarioByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFuncionarioById", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.GetFuncionarioByIdRequestBody Body;
        
        public GetFuncionarioByIdRequest()
        {
        }
        
        public GetFuncionarioByIdRequest(AsmxService.GetFuncionarioByIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFuncionarioByIdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetFuncionarioByIdRequestBody()
        {
        }
        
        public GetFuncionarioByIdRequestBody(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFuncionarioByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFuncionarioByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.GetFuncionarioByIdResponseBody Body;
        
        public GetFuncionarioByIdResponse()
        {
        }
        
        public GetFuncionarioByIdResponse(AsmxService.GetFuncionarioByIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFuncionarioByIdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AsmxService.Funcionario GetFuncionarioByIdResult;
        
        public GetFuncionarioByIdResponseBody()
        {
        }
        
        public GetFuncionarioByIdResponseBody(AsmxService.Funcionario GetFuncionarioByIdResult)
        {
            this.GetFuncionarioByIdResult = GetFuncionarioByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateFuncionarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateFuncionario", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.CreateFuncionarioRequestBody Body;
        
        public CreateFuncionarioRequest()
        {
        }
        
        public CreateFuncionarioRequest(AsmxService.CreateFuncionarioRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateFuncionarioRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AsmxService.Funcionario funcionario;
        
        public CreateFuncionarioRequestBody()
        {
        }
        
        public CreateFuncionarioRequestBody(AsmxService.Funcionario funcionario)
        {
            this.funcionario = funcionario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateFuncionarioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateFuncionarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.CreateFuncionarioResponseBody Body;
        
        public CreateFuncionarioResponse()
        {
        }
        
        public CreateFuncionarioResponse(AsmxService.CreateFuncionarioResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateFuncionarioResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateFuncionarioResult;
        
        public CreateFuncionarioResponseBody()
        {
        }
        
        public CreateFuncionarioResponseBody(bool CreateFuncionarioResult)
        {
            this.CreateFuncionarioResult = CreateFuncionarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFuncionarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFuncionario", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.UpdateFuncionarioRequestBody Body;
        
        public UpdateFuncionarioRequest()
        {
        }
        
        public UpdateFuncionarioRequest(AsmxService.UpdateFuncionarioRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateFuncionarioRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AsmxService.Funcionario funcionario;
        
        public UpdateFuncionarioRequestBody()
        {
        }
        
        public UpdateFuncionarioRequestBody(AsmxService.Funcionario funcionario)
        {
            this.funcionario = funcionario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFuncionarioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFuncionarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.UpdateFuncionarioResponseBody Body;
        
        public UpdateFuncionarioResponse()
        {
        }
        
        public UpdateFuncionarioResponse(AsmxService.UpdateFuncionarioResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateFuncionarioResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateFuncionarioResult;
        
        public UpdateFuncionarioResponseBody()
        {
        }
        
        public UpdateFuncionarioResponseBody(bool UpdateFuncionarioResult)
        {
            this.UpdateFuncionarioResult = UpdateFuncionarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUtentesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUtentes", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.GetAllUtentesRequestBody Body;
        
        public GetAllUtentesRequest()
        {
        }
        
        public GetAllUtentesRequest(AsmxService.GetAllUtentesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUtentesRequestBody
    {
        
        public GetAllUtentesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUtentesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUtentesResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.GetAllUtentesResponseBody Body;
        
        public GetAllUtentesResponse()
        {
        }
        
        public GetAllUtentesResponse(AsmxService.GetAllUtentesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllUtentesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AsmxService.Utente[] GetAllUtentesResult;
        
        public GetAllUtentesResponseBody()
        {
        }
        
        public GetAllUtentesResponseBody(AsmxService.Utente[] GetAllUtentesResult)
        {
            this.GetAllUtentesResult = GetAllUtentesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUtenteByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUtenteById", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.GetUtenteByIdRequestBody Body;
        
        public GetUtenteByIdRequest()
        {
        }
        
        public GetUtenteByIdRequest(AsmxService.GetUtenteByIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUtenteByIdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetUtenteByIdRequestBody()
        {
        }
        
        public GetUtenteByIdRequestBody(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUtenteByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUtenteByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.GetUtenteByIdResponseBody Body;
        
        public GetUtenteByIdResponse()
        {
        }
        
        public GetUtenteByIdResponse(AsmxService.GetUtenteByIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUtenteByIdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AsmxService.Utente GetUtenteByIdResult;
        
        public GetUtenteByIdResponseBody()
        {
        }
        
        public GetUtenteByIdResponseBody(AsmxService.Utente GetUtenteByIdResult)
        {
            this.GetUtenteByIdResult = GetUtenteByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUtenteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUtente", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.CreateUtenteRequestBody Body;
        
        public CreateUtenteRequest()
        {
        }
        
        public CreateUtenteRequest(AsmxService.CreateUtenteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUtenteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int NIF;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime dataEntrada;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int tipoUtenteId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int hospitalId;
        
        public CreateUtenteRequestBody()
        {
        }
        
        public CreateUtenteRequestBody(string nome, int NIF, System.DateTime dataEntrada, int tipoUtenteId, int hospitalId)
        {
            this.nome = nome;
            this.NIF = NIF;
            this.dataEntrada = dataEntrada;
            this.tipoUtenteId = tipoUtenteId;
            this.hospitalId = hospitalId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUtenteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUtenteResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.CreateUtenteResponseBody Body;
        
        public CreateUtenteResponse()
        {
        }
        
        public CreateUtenteResponse(AsmxService.CreateUtenteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUtenteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateUtenteResult;
        
        public CreateUtenteResponseBody()
        {
        }
        
        public CreateUtenteResponseBody(bool CreateUtenteResult)
        {
            this.CreateUtenteResult = CreateUtenteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUtenteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUtente", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.UpdateUtenteRequestBody Body;
        
        public UpdateUtenteRequest()
        {
        }
        
        public UpdateUtenteRequest(AsmxService.UpdateUtenteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUtenteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int nif;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dataEntrada;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int tipoUtenteId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int hospitalId;
        
        public UpdateUtenteRequestBody()
        {
        }
        
        public UpdateUtenteRequestBody(int id, string nome, int nif, System.DateTime dataEntrada, int tipoUtenteId, int hospitalId)
        {
            this.id = id;
            this.nome = nome;
            this.nif = nif;
            this.dataEntrada = dataEntrada;
            this.tipoUtenteId = tipoUtenteId;
            this.hospitalId = hospitalId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUtenteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUtenteResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.UpdateUtenteResponseBody Body;
        
        public UpdateUtenteResponse()
        {
        }
        
        public UpdateUtenteResponse(AsmxService.UpdateUtenteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUtenteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateUtenteResult;
        
        public UpdateUtenteResponseBody()
        {
        }
        
        public UpdateUtenteResponseBody(bool UpdateUtenteResult)
        {
            this.UpdateUtenteResult = UpdateUtenteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateConsultaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateConsulta", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.CreateConsultaRequestBody Body;
        
        public CreateConsultaRequest()
        {
        }
        
        public CreateConsultaRequest(AsmxService.CreateConsultaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateConsultaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int utenteId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int funcionarioId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int hospitalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int medicoId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public AsmxService.TimeSpan hora;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string descricao;
        
        public CreateConsultaRequestBody()
        {
        }
        
        public CreateConsultaRequestBody(int utenteId, int funcionarioId, int hospitalId, int medicoId, System.DateTime data, AsmxService.TimeSpan hora, string descricao)
        {
            this.utenteId = utenteId;
            this.funcionarioId = funcionarioId;
            this.hospitalId = hospitalId;
            this.medicoId = medicoId;
            this.data = data;
            this.hora = hora;
            this.descricao = descricao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateConsultaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateConsultaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.CreateConsultaResponseBody Body;
        
        public CreateConsultaResponse()
        {
        }
        
        public CreateConsultaResponse(AsmxService.CreateConsultaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateConsultaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateConsultaResult;
        
        public CreateConsultaResponseBody()
        {
        }
        
        public CreateConsultaResponseBody(bool CreateConsultaResult)
        {
            this.CreateConsultaResult = CreateConsultaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllConsultasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllConsultas", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.GetAllConsultasRequestBody Body;
        
        public GetAllConsultasRequest()
        {
        }
        
        public GetAllConsultasRequest(AsmxService.GetAllConsultasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllConsultasRequestBody
    {
        
        public GetAllConsultasRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllConsultasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllConsultasResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.GetAllConsultasResponseBody Body;
        
        public GetAllConsultasResponse()
        {
        }
        
        public GetAllConsultasResponse(AsmxService.GetAllConsultasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllConsultasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AsmxService.Consulta[] GetAllConsultasResult;
        
        public GetAllConsultasResponseBody()
        {
        }
        
        public GetAllConsultasResponseBody(AsmxService.Consulta[] GetAllConsultasResult)
        {
            this.GetAllConsultasResult = GetAllConsultasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateConsultaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateConsulta", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.UpdateConsultaRequestBody Body;
        
        public UpdateConsultaRequest()
        {
        }
        
        public UpdateConsultaRequest(AsmxService.UpdateConsultaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateConsultaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int utenteId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int funcionarioId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int hospitalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int medicoId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public AsmxService.TimeSpan hora;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string descricao;
        
        public UpdateConsultaRequestBody()
        {
        }
        
        public UpdateConsultaRequestBody(int utenteId, int funcionarioId, int hospitalId, int medicoId, System.DateTime data, AsmxService.TimeSpan hora, string descricao)
        {
            this.utenteId = utenteId;
            this.funcionarioId = funcionarioId;
            this.hospitalId = hospitalId;
            this.medicoId = medicoId;
            this.data = data;
            this.hora = hora;
            this.descricao = descricao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateConsultaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateConsultaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.UpdateConsultaResponseBody Body;
        
        public UpdateConsultaResponse()
        {
        }
        
        public UpdateConsultaResponse(AsmxService.UpdateConsultaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateConsultaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateConsultaResult;
        
        public UpdateConsultaResponseBody()
        {
        }
        
        public UpdateConsultaResponseBody(bool UpdateConsultaResult)
        {
            this.UpdateConsultaResult = UpdateConsultaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaByHospitalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaByHospital", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.ConsultaByHospitalRequestBody Body;
        
        public ConsultaByHospitalRequest()
        {
        }
        
        public ConsultaByHospitalRequest(AsmxService.ConsultaByHospitalRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaByHospitalRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int hospitalId;
        
        public ConsultaByHospitalRequestBody()
        {
        }
        
        public ConsultaByHospitalRequestBody(int hospitalId)
        {
            this.hospitalId = hospitalId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaByHospitalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaByHospitalResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.ConsultaByHospitalResponseBody Body;
        
        public ConsultaByHospitalResponse()
        {
        }
        
        public ConsultaByHospitalResponse(AsmxService.ConsultaByHospitalResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaByHospitalResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AsmxService.Consulta[] ConsultaByHospitalResult;
        
        public ConsultaByHospitalResponseBody()
        {
        }
        
        public ConsultaByHospitalResponseBody(AsmxService.Consulta[] ConsultaByHospitalResult)
        {
            this.ConsultaByHospitalResult = ConsultaByHospitalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaByUtenteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaByUtente", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.ConsultaByUtenteRequestBody Body;
        
        public ConsultaByUtenteRequest()
        {
        }
        
        public ConsultaByUtenteRequest(AsmxService.ConsultaByUtenteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaByUtenteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int utenteId;
        
        public ConsultaByUtenteRequestBody()
        {
        }
        
        public ConsultaByUtenteRequestBody(int utenteId)
        {
            this.utenteId = utenteId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaByUtenteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaByUtenteResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.ConsultaByUtenteResponseBody Body;
        
        public ConsultaByUtenteResponse()
        {
        }
        
        public ConsultaByUtenteResponse(AsmxService.ConsultaByUtenteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaByUtenteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AsmxService.Consulta[] ConsultaByUtenteResult;
        
        public ConsultaByUtenteResponseBody()
        {
        }
        
        public ConsultaByUtenteResponseBody(AsmxService.Consulta[] ConsultaByUtenteResult)
        {
            this.ConsultaByUtenteResult = ConsultaByUtenteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaByFuncionarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaByFuncionario", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.ConsultaByFuncionarioRequestBody Body;
        
        public ConsultaByFuncionarioRequest()
        {
        }
        
        public ConsultaByFuncionarioRequest(AsmxService.ConsultaByFuncionarioRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaByFuncionarioRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int funcionarioId;
        
        public ConsultaByFuncionarioRequestBody()
        {
        }
        
        public ConsultaByFuncionarioRequestBody(int funcionarioId)
        {
            this.funcionarioId = funcionarioId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaByFuncionarioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaByFuncionarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.ConsultaByFuncionarioResponseBody Body;
        
        public ConsultaByFuncionarioResponse()
        {
        }
        
        public ConsultaByFuncionarioResponse(AsmxService.ConsultaByFuncionarioResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaByFuncionarioResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AsmxService.Consulta[] ConsultaByFuncionarioResult;
        
        public ConsultaByFuncionarioResponseBody()
        {
        }
        
        public ConsultaByFuncionarioResponseBody(AsmxService.Consulta[] ConsultaByFuncionarioResult)
        {
            this.ConsultaByFuncionarioResult = ConsultaByFuncionarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaById", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.ConsultaByIdRequestBody Body;
        
        public ConsultaByIdRequest()
        {
        }
        
        public ConsultaByIdRequest(AsmxService.ConsultaByIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaByIdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ConsultaByIdRequestBody()
        {
        }
        
        public ConsultaByIdRequestBody(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxService.ConsultaByIdResponseBody Body;
        
        public ConsultaByIdResponse()
        {
        }
        
        public ConsultaByIdResponse(AsmxService.ConsultaByIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaByIdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AsmxService.Consulta ConsultaByIdResult;
        
        public ConsultaByIdResponseBody()
        {
        }
        
        public ConsultaByIdResponseBody(AsmxService.Consulta ConsultaByIdResult)
        {
            this.ConsultaByIdResult = ConsultaByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface HospitalServiceSoapChannel : AsmxService.HospitalServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class HospitalServiceSoapClient : System.ServiceModel.ClientBase<AsmxService.HospitalServiceSoap>, AsmxService.HospitalServiceSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HospitalServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(HospitalServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), HospitalServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HospitalServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HospitalServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HospitalServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HospitalServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HospitalServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxService.GetAllFuncionariosResponse> AsmxService.HospitalServiceSoap.GetAllFuncionariosAsync(AsmxService.GetAllFuncionariosRequest request)
        {
            return base.Channel.GetAllFuncionariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxService.GetAllFuncionariosResponse> GetAllFuncionariosAsync()
        {
            AsmxService.GetAllFuncionariosRequest inValue = new AsmxService.GetAllFuncionariosRequest();
            inValue.Body = new AsmxService.GetAllFuncionariosRequestBody();
            return ((AsmxService.HospitalServiceSoap)(this)).GetAllFuncionariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxService.GetFuncionarioByIdResponse> AsmxService.HospitalServiceSoap.GetFuncionarioByIdAsync(AsmxService.GetFuncionarioByIdRequest request)
        {
            return base.Channel.GetFuncionarioByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxService.GetFuncionarioByIdResponse> GetFuncionarioByIdAsync(int id)
        {
            AsmxService.GetFuncionarioByIdRequest inValue = new AsmxService.GetFuncionarioByIdRequest();
            inValue.Body = new AsmxService.GetFuncionarioByIdRequestBody();
            inValue.Body.id = id;
            return ((AsmxService.HospitalServiceSoap)(this)).GetFuncionarioByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxService.CreateFuncionarioResponse> AsmxService.HospitalServiceSoap.CreateFuncionarioAsync(AsmxService.CreateFuncionarioRequest request)
        {
            return base.Channel.CreateFuncionarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxService.CreateFuncionarioResponse> CreateFuncionarioAsync(AsmxService.Funcionario funcionario)
        {
            AsmxService.CreateFuncionarioRequest inValue = new AsmxService.CreateFuncionarioRequest();
            inValue.Body = new AsmxService.CreateFuncionarioRequestBody();
            inValue.Body.funcionario = funcionario;
            return ((AsmxService.HospitalServiceSoap)(this)).CreateFuncionarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxService.UpdateFuncionarioResponse> AsmxService.HospitalServiceSoap.UpdateFuncionarioAsync(AsmxService.UpdateFuncionarioRequest request)
        {
            return base.Channel.UpdateFuncionarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxService.UpdateFuncionarioResponse> UpdateFuncionarioAsync(AsmxService.Funcionario funcionario)
        {
            AsmxService.UpdateFuncionarioRequest inValue = new AsmxService.UpdateFuncionarioRequest();
            inValue.Body = new AsmxService.UpdateFuncionarioRequestBody();
            inValue.Body.funcionario = funcionario;
            return ((AsmxService.HospitalServiceSoap)(this)).UpdateFuncionarioAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteFuncionarioAsync(int id)
        {
            return base.Channel.DeleteFuncionarioAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxService.GetAllUtentesResponse> AsmxService.HospitalServiceSoap.GetAllUtentesAsync(AsmxService.GetAllUtentesRequest request)
        {
            return base.Channel.GetAllUtentesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxService.GetAllUtentesResponse> GetAllUtentesAsync()
        {
            AsmxService.GetAllUtentesRequest inValue = new AsmxService.GetAllUtentesRequest();
            inValue.Body = new AsmxService.GetAllUtentesRequestBody();
            return ((AsmxService.HospitalServiceSoap)(this)).GetAllUtentesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxService.GetUtenteByIdResponse> AsmxService.HospitalServiceSoap.GetUtenteByIdAsync(AsmxService.GetUtenteByIdRequest request)
        {
            return base.Channel.GetUtenteByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxService.GetUtenteByIdResponse> GetUtenteByIdAsync(int id)
        {
            AsmxService.GetUtenteByIdRequest inValue = new AsmxService.GetUtenteByIdRequest();
            inValue.Body = new AsmxService.GetUtenteByIdRequestBody();
            inValue.Body.id = id;
            return ((AsmxService.HospitalServiceSoap)(this)).GetUtenteByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxService.CreateUtenteResponse> AsmxService.HospitalServiceSoap.CreateUtenteAsync(AsmxService.CreateUtenteRequest request)
        {
            return base.Channel.CreateUtenteAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxService.CreateUtenteResponse> CreateUtenteAsync(string nome, int NIF, System.DateTime dataEntrada, int tipoUtenteId, int hospitalId)
        {
            AsmxService.CreateUtenteRequest inValue = new AsmxService.CreateUtenteRequest();
            inValue.Body = new AsmxService.CreateUtenteRequestBody();
            inValue.Body.nome = nome;
            inValue.Body.NIF = NIF;
            inValue.Body.dataEntrada = dataEntrada;
            inValue.Body.tipoUtenteId = tipoUtenteId;
            inValue.Body.hospitalId = hospitalId;
            return ((AsmxService.HospitalServiceSoap)(this)).CreateUtenteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxService.UpdateUtenteResponse> AsmxService.HospitalServiceSoap.UpdateUtenteAsync(AsmxService.UpdateUtenteRequest request)
        {
            return base.Channel.UpdateUtenteAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxService.UpdateUtenteResponse> UpdateUtenteAsync(int id, string nome, int nif, System.DateTime dataEntrada, int tipoUtenteId, int hospitalId)
        {
            AsmxService.UpdateUtenteRequest inValue = new AsmxService.UpdateUtenteRequest();
            inValue.Body = new AsmxService.UpdateUtenteRequestBody();
            inValue.Body.id = id;
            inValue.Body.nome = nome;
            inValue.Body.nif = nif;
            inValue.Body.dataEntrada = dataEntrada;
            inValue.Body.tipoUtenteId = tipoUtenteId;
            inValue.Body.hospitalId = hospitalId;
            return ((AsmxService.HospitalServiceSoap)(this)).UpdateUtenteAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUtenteAsync(int id)
        {
            return base.Channel.DeleteUtenteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxService.CreateConsultaResponse> AsmxService.HospitalServiceSoap.CreateConsultaAsync(AsmxService.CreateConsultaRequest request)
        {
            return base.Channel.CreateConsultaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxService.CreateConsultaResponse> CreateConsultaAsync(int utenteId, int funcionarioId, int hospitalId, int medicoId, System.DateTime data, AsmxService.TimeSpan hora, string descricao)
        {
            AsmxService.CreateConsultaRequest inValue = new AsmxService.CreateConsultaRequest();
            inValue.Body = new AsmxService.CreateConsultaRequestBody();
            inValue.Body.utenteId = utenteId;
            inValue.Body.funcionarioId = funcionarioId;
            inValue.Body.hospitalId = hospitalId;
            inValue.Body.medicoId = medicoId;
            inValue.Body.data = data;
            inValue.Body.hora = hora;
            inValue.Body.descricao = descricao;
            return ((AsmxService.HospitalServiceSoap)(this)).CreateConsultaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxService.GetAllConsultasResponse> AsmxService.HospitalServiceSoap.GetAllConsultasAsync(AsmxService.GetAllConsultasRequest request)
        {
            return base.Channel.GetAllConsultasAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxService.GetAllConsultasResponse> GetAllConsultasAsync()
        {
            AsmxService.GetAllConsultasRequest inValue = new AsmxService.GetAllConsultasRequest();
            inValue.Body = new AsmxService.GetAllConsultasRequestBody();
            return ((AsmxService.HospitalServiceSoap)(this)).GetAllConsultasAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteConsultaAsync(int id)
        {
            return base.Channel.DeleteConsultaAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxService.UpdateConsultaResponse> AsmxService.HospitalServiceSoap.UpdateConsultaAsync(AsmxService.UpdateConsultaRequest request)
        {
            return base.Channel.UpdateConsultaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxService.UpdateConsultaResponse> UpdateConsultaAsync(int utenteId, int funcionarioId, int hospitalId, int medicoId, System.DateTime data, AsmxService.TimeSpan hora, string descricao)
        {
            AsmxService.UpdateConsultaRequest inValue = new AsmxService.UpdateConsultaRequest();
            inValue.Body = new AsmxService.UpdateConsultaRequestBody();
            inValue.Body.utenteId = utenteId;
            inValue.Body.funcionarioId = funcionarioId;
            inValue.Body.hospitalId = hospitalId;
            inValue.Body.medicoId = medicoId;
            inValue.Body.data = data;
            inValue.Body.hora = hora;
            inValue.Body.descricao = descricao;
            return ((AsmxService.HospitalServiceSoap)(this)).UpdateConsultaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxService.ConsultaByHospitalResponse> AsmxService.HospitalServiceSoap.ConsultaByHospitalAsync(AsmxService.ConsultaByHospitalRequest request)
        {
            return base.Channel.ConsultaByHospitalAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxService.ConsultaByHospitalResponse> ConsultaByHospitalAsync(int hospitalId)
        {
            AsmxService.ConsultaByHospitalRequest inValue = new AsmxService.ConsultaByHospitalRequest();
            inValue.Body = new AsmxService.ConsultaByHospitalRequestBody();
            inValue.Body.hospitalId = hospitalId;
            return ((AsmxService.HospitalServiceSoap)(this)).ConsultaByHospitalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxService.ConsultaByUtenteResponse> AsmxService.HospitalServiceSoap.ConsultaByUtenteAsync(AsmxService.ConsultaByUtenteRequest request)
        {
            return base.Channel.ConsultaByUtenteAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxService.ConsultaByUtenteResponse> ConsultaByUtenteAsync(int utenteId)
        {
            AsmxService.ConsultaByUtenteRequest inValue = new AsmxService.ConsultaByUtenteRequest();
            inValue.Body = new AsmxService.ConsultaByUtenteRequestBody();
            inValue.Body.utenteId = utenteId;
            return ((AsmxService.HospitalServiceSoap)(this)).ConsultaByUtenteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxService.ConsultaByFuncionarioResponse> AsmxService.HospitalServiceSoap.ConsultaByFuncionarioAsync(AsmxService.ConsultaByFuncionarioRequest request)
        {
            return base.Channel.ConsultaByFuncionarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxService.ConsultaByFuncionarioResponse> ConsultaByFuncionarioAsync(int funcionarioId)
        {
            AsmxService.ConsultaByFuncionarioRequest inValue = new AsmxService.ConsultaByFuncionarioRequest();
            inValue.Body = new AsmxService.ConsultaByFuncionarioRequestBody();
            inValue.Body.funcionarioId = funcionarioId;
            return ((AsmxService.HospitalServiceSoap)(this)).ConsultaByFuncionarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxService.ConsultaByIdResponse> AsmxService.HospitalServiceSoap.ConsultaByIdAsync(AsmxService.ConsultaByIdRequest request)
        {
            return base.Channel.ConsultaByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxService.ConsultaByIdResponse> ConsultaByIdAsync(int id)
        {
            AsmxService.ConsultaByIdRequest inValue = new AsmxService.ConsultaByIdRequest();
            inValue.Body = new AsmxService.ConsultaByIdRequestBody();
            inValue.Body.id = id;
            return ((AsmxService.HospitalServiceSoap)(this)).ConsultaByIdAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HospitalServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HospitalServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HospitalServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44347/Services/HospitalService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.HospitalServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44347/Services/HospitalService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HospitalServiceSoap,
            
            HospitalServiceSoap12,
        }
    }
}
