//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFHospitalService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Medico", Namespace="http://schemas.datacontract.org/2004/07/ISITP02.Models")]
    public partial class Medico : object
    {
        
        private WCFHospitalService.Consulta[] ConsultasField;
        
        private int IdField;
        
        private string NomeField;
        
        private WCFHospitalService.TipoMedico TipoMedicoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFHospitalService.Consulta[] Consultas
        {
            get
            {
                return this.ConsultasField;
            }
            set
            {
                this.ConsultasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFHospitalService.TipoMedico TipoMedico
        {
            get
            {
                return this.TipoMedicoField;
            }
            set
            {
                this.TipoMedicoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoMedico", Namespace="http://schemas.datacontract.org/2004/07/ISITP02.Models")]
    public partial class TipoMedico : object
    {
        
        private string DescricaoField;
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Consulta", Namespace="http://schemas.datacontract.org/2004/07/ISITP02.Models")]
    public partial class Consulta : object
    {
        
        private System.DateTime DataField;
        
        private string DescricaoField;
        
        private WCFHospitalService.Funcionario FuncionarioField;
        
        private int FuncionarioIdField;
        
        private System.TimeSpan HoraField;
        
        private WCFHospitalService.Hospital HospitalField;
        
        private int HospitalIdField;
        
        private int IdField;
        
        private WCFHospitalService.Medico MedicoField;
        
        private int MedicoIdField;
        
        private WCFHospitalService.Utente UtenteField;
        
        private int UtenteIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFHospitalService.Funcionario Funcionario
        {
            get
            {
                return this.FuncionarioField;
            }
            set
            {
                this.FuncionarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FuncionarioId
        {
            get
            {
                return this.FuncionarioIdField;
            }
            set
            {
                this.FuncionarioIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Hora
        {
            get
            {
                return this.HoraField;
            }
            set
            {
                this.HoraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFHospitalService.Hospital Hospital
        {
            get
            {
                return this.HospitalField;
            }
            set
            {
                this.HospitalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HospitalId
        {
            get
            {
                return this.HospitalIdField;
            }
            set
            {
                this.HospitalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFHospitalService.Medico Medico
        {
            get
            {
                return this.MedicoField;
            }
            set
            {
                this.MedicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MedicoId
        {
            get
            {
                return this.MedicoIdField;
            }
            set
            {
                this.MedicoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFHospitalService.Utente Utente
        {
            get
            {
                return this.UtenteField;
            }
            set
            {
                this.UtenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UtenteId
        {
            get
            {
                return this.UtenteIdField;
            }
            set
            {
                this.UtenteIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Funcionario", Namespace="http://schemas.datacontract.org/2004/07/ISITP02.Models")]
    public partial class Funcionario : object
    {
        
        private WCFHospitalService.Consulta[] ConsultasField;
        
        private int ContactoField;
        
        private System.DateTime DataEntradaField;
        
        private int IdField;
        
        private int NIFField;
        
        private string NomeField;
        
        private string PasswordField;
        
        private WCFHospitalService.TipoFuncionario TipoFuncionarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFHospitalService.Consulta[] Consultas
        {
            get
            {
                return this.ConsultasField;
            }
            set
            {
                this.ConsultasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Contacto
        {
            get
            {
                return this.ContactoField;
            }
            set
            {
                this.ContactoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataEntrada
        {
            get
            {
                return this.DataEntradaField;
            }
            set
            {
                this.DataEntradaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NIF
        {
            get
            {
                return this.NIFField;
            }
            set
            {
                this.NIFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFHospitalService.TipoFuncionario TipoFuncionario
        {
            get
            {
                return this.TipoFuncionarioField;
            }
            set
            {
                this.TipoFuncionarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hospital", Namespace="http://schemas.datacontract.org/2004/07/ISITP02.Models")]
    public partial class Hospital : object
    {
        
        private WCFHospitalService.Consulta[] ConsultasField;
        
        private int IdField;
        
        private string LocalizacaoField;
        
        private string NomeField;
        
        private WCFHospitalService.Utente[] UtentesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFHospitalService.Consulta[] Consultas
        {
            get
            {
                return this.ConsultasField;
            }
            set
            {
                this.ConsultasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localizacao
        {
            get
            {
                return this.LocalizacaoField;
            }
            set
            {
                this.LocalizacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFHospitalService.Utente[] Utentes
        {
            get
            {
                return this.UtentesField;
            }
            set
            {
                this.UtentesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Utente", Namespace="http://schemas.datacontract.org/2004/07/ISITP02.Models")]
    public partial class Utente : object
    {
        
        private WCFHospitalService.Consulta[] ConsultasField;
        
        private System.DateTime DataEntradaField;
        
        private WCFHospitalService.Hospital HospitalField;
        
        private int IdField;
        
        private int NIFField;
        
        private string NomeField;
        
        private WCFHospitalService.TipoUtente TipoUtenteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFHospitalService.Consulta[] Consultas
        {
            get
            {
                return this.ConsultasField;
            }
            set
            {
                this.ConsultasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataEntrada
        {
            get
            {
                return this.DataEntradaField;
            }
            set
            {
                this.DataEntradaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFHospitalService.Hospital Hospital
        {
            get
            {
                return this.HospitalField;
            }
            set
            {
                this.HospitalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NIF
        {
            get
            {
                return this.NIFField;
            }
            set
            {
                this.NIFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFHospitalService.TipoUtente TipoUtente
        {
            get
            {
                return this.TipoUtenteField;
            }
            set
            {
                this.TipoUtenteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoFuncionario", Namespace="http://schemas.datacontract.org/2004/07/ISITP02.Models")]
    public partial class TipoFuncionario : object
    {
        
        private string DescricaoField;
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoUtente", Namespace="http://schemas.datacontract.org/2004/07/ISITP02.Models")]
    public partial class TipoUtente : object
    {
        
        private string DescricaoField;
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFHospitalService.IHospitalService")]
    public interface IHospitalService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/CreateMedico", ReplyAction="http://tempuri.org/IHospitalService/CreateMedicoResponse")]
        System.Threading.Tasks.Task<bool> CreateMedicoAsync(string nome, int tipoMedicoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GetAllMedicos", ReplyAction="http://tempuri.org/IHospitalService/GetAllMedicosResponse")]
        System.Threading.Tasks.Task<WCFHospitalService.Medico[]> GetAllMedicosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GetMedicoById", ReplyAction="http://tempuri.org/IHospitalService/GetMedicoByIdResponse")]
        System.Threading.Tasks.Task<WCFHospitalService.Medico> GetMedicoByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/UpdateMedico", ReplyAction="http://tempuri.org/IHospitalService/UpdateMedicoResponse")]
        System.Threading.Tasks.Task<bool> UpdateMedicoAsync(int id, string nome, int tipoMedicoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/DeleteMedico", ReplyAction="http://tempuri.org/IHospitalService/DeleteMedicoResponse")]
        System.Threading.Tasks.Task<bool> DeleteMedicoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/CreateTipoMedico", ReplyAction="http://tempuri.org/IHospitalService/CreateTipoMedicoResponse")]
        System.Threading.Tasks.Task<bool> CreateTipoMedicoAsync(string descricao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/DeleteTipoMedico", ReplyAction="http://tempuri.org/IHospitalService/DeleteTipoMedicoResponse")]
        System.Threading.Tasks.Task<bool> DeleteTipoMedicoAsync(string descricao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/CreateHospital", ReplyAction="http://tempuri.org/IHospitalService/CreateHospitalResponse")]
        System.Threading.Tasks.Task<bool> CreateHospitalAsync(string nome, string localizacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GETALLHOSPITAIS", ReplyAction="http://tempuri.org/IHospitalService/GETALLHOSPITAISResponse")]
        System.Threading.Tasks.Task<WCFHospitalService.Hospital[]> GETALLHOSPITAISAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GetHospitalByLoc", ReplyAction="http://tempuri.org/IHospitalService/GetHospitalByLocResponse")]
        System.Threading.Tasks.Task<WCFHospitalService.Hospital> GetHospitalByLocAsync(string localização);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/CreateConsulta", ReplyAction="http://tempuri.org/IHospitalService/CreateConsultaResponse")]
        System.Threading.Tasks.Task<bool> CreateConsultaAsync(int utenteId, int funcionarioId, int hospitalId, int medicoId, System.DateTime data, System.TimeSpan hora, string descricao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GetAllConsultas", ReplyAction="http://tempuri.org/IHospitalService/GetAllConsultasResponse")]
        System.Threading.Tasks.Task<WCFHospitalService.Consulta[]> GetAllConsultasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/deleteConsulta", ReplyAction="http://tempuri.org/IHospitalService/deleteConsultaResponse")]
        System.Threading.Tasks.Task<bool> deleteConsultaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/UpdateConsulta", ReplyAction="http://tempuri.org/IHospitalService/UpdateConsultaResponse")]
        System.Threading.Tasks.Task<bool> UpdateConsultaAsync(int UtenteId, int FuncionarioId, int hospitalId, int medicoId, System.DateTime data, System.TimeSpan hora, string descricao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/ConsultaById", ReplyAction="http://tempuri.org/IHospitalService/ConsultaByIdResponse")]
        System.Threading.Tasks.Task<WCFHospitalService.Consulta> ConsultaByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/ConsultaByHospital", ReplyAction="http://tempuri.org/IHospitalService/ConsultaByHospitalResponse")]
        System.Threading.Tasks.Task<WCFHospitalService.Consulta[]> ConsultaByHospitalAsync(int hospitalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/ConsultaByUtente", ReplyAction="http://tempuri.org/IHospitalService/ConsultaByUtenteResponse")]
        System.Threading.Tasks.Task<WCFHospitalService.Consulta[]> ConsultaByUtenteAsync(int utenteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/ConsultaByFuncionario", ReplyAction="http://tempuri.org/IHospitalService/ConsultaByFuncionarioResponse")]
        System.Threading.Tasks.Task<WCFHospitalService.Consulta[]> ConsultaByFuncionarioAsync(int funcionarioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/AutenticarUtilizador", ReplyAction="http://tempuri.org/IHospitalService/AutenticarUtilizadorResponse")]
        System.Threading.Tasks.Task<WCFHospitalService.Funcionario> AutenticarUtilizadorAsync(WCFHospitalService.Funcionario f);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IHospitalServiceChannel : WCFHospitalService.IHospitalService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class HospitalServiceClient : System.ServiceModel.ClientBase<WCFHospitalService.IHospitalService>, WCFHospitalService.IHospitalService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HospitalServiceClient() : 
                base(HospitalServiceClient.GetDefaultBinding(), HospitalServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IHospitalService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HospitalServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(HospitalServiceClient.GetBindingForEndpoint(endpointConfiguration), HospitalServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HospitalServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HospitalServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HospitalServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HospitalServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HospitalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> CreateMedicoAsync(string nome, int tipoMedicoId)
        {
            return base.Channel.CreateMedicoAsync(nome, tipoMedicoId);
        }
        
        public System.Threading.Tasks.Task<WCFHospitalService.Medico[]> GetAllMedicosAsync()
        {
            return base.Channel.GetAllMedicosAsync();
        }
        
        public System.Threading.Tasks.Task<WCFHospitalService.Medico> GetMedicoByIdAsync(int id)
        {
            return base.Channel.GetMedicoByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateMedicoAsync(int id, string nome, int tipoMedicoId)
        {
            return base.Channel.UpdateMedicoAsync(id, nome, tipoMedicoId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteMedicoAsync(int id)
        {
            return base.Channel.DeleteMedicoAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> CreateTipoMedicoAsync(string descricao)
        {
            return base.Channel.CreateTipoMedicoAsync(descricao);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteTipoMedicoAsync(string descricao)
        {
            return base.Channel.DeleteTipoMedicoAsync(descricao);
        }
        
        public System.Threading.Tasks.Task<bool> CreateHospitalAsync(string nome, string localizacao)
        {
            return base.Channel.CreateHospitalAsync(nome, localizacao);
        }
        
        public System.Threading.Tasks.Task<WCFHospitalService.Hospital[]> GETALLHOSPITAISAsync()
        {
            return base.Channel.GETALLHOSPITAISAsync();
        }
        
        public System.Threading.Tasks.Task<WCFHospitalService.Hospital> GetHospitalByLocAsync(string localização)
        {
            return base.Channel.GetHospitalByLocAsync(localização);
        }
        
        public System.Threading.Tasks.Task<bool> CreateConsultaAsync(int utenteId, int funcionarioId, int hospitalId, int medicoId, System.DateTime data, System.TimeSpan hora, string descricao)
        {
            return base.Channel.CreateConsultaAsync(utenteId, funcionarioId, hospitalId, medicoId, data, hora, descricao);
        }
        
        public System.Threading.Tasks.Task<WCFHospitalService.Consulta[]> GetAllConsultasAsync()
        {
            return base.Channel.GetAllConsultasAsync();
        }
        
        public System.Threading.Tasks.Task<bool> deleteConsultaAsync(int id)
        {
            return base.Channel.deleteConsultaAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateConsultaAsync(int UtenteId, int FuncionarioId, int hospitalId, int medicoId, System.DateTime data, System.TimeSpan hora, string descricao)
        {
            return base.Channel.UpdateConsultaAsync(UtenteId, FuncionarioId, hospitalId, medicoId, data, hora, descricao);
        }
        
        public System.Threading.Tasks.Task<WCFHospitalService.Consulta> ConsultaByIdAsync(int id)
        {
            return base.Channel.ConsultaByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<WCFHospitalService.Consulta[]> ConsultaByHospitalAsync(int hospitalId)
        {
            return base.Channel.ConsultaByHospitalAsync(hospitalId);
        }
        
        public System.Threading.Tasks.Task<WCFHospitalService.Consulta[]> ConsultaByUtenteAsync(int utenteId)
        {
            return base.Channel.ConsultaByUtenteAsync(utenteId);
        }
        
        public System.Threading.Tasks.Task<WCFHospitalService.Consulta[]> ConsultaByFuncionarioAsync(int funcionarioId)
        {
            return base.Channel.ConsultaByFuncionarioAsync(funcionarioId);
        }
        
        public System.Threading.Tasks.Task<WCFHospitalService.Funcionario> AutenticarUtilizadorAsync(WCFHospitalService.Funcionario f)
        {
            return base.Channel.AutenticarUtilizadorAsync(f);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IHospitalService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IHospitalService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:57645/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return HospitalServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IHospitalService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return HospitalServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IHospitalService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IHospitalService,
        }
    }
}
