//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISI_TP02_Forms.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Medico", Namespace="http://schemas.datacontract.org/2004/07/ISITP02.Models")]
    [System.SerializableAttribute()]
    public partial class Medico : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ISI_TP02_Forms.ServiceReference2.Consulta[] ConsultasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ISI_TP02_Forms.ServiceReference2.TipoMedico TipoMedicoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ISI_TP02_Forms.ServiceReference2.Consulta[] Consultas {
            get {
                return this.ConsultasField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsultasField, value) != true)) {
                    this.ConsultasField = value;
                    this.RaisePropertyChanged("Consultas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ISI_TP02_Forms.ServiceReference2.TipoMedico TipoMedico {
            get {
                return this.TipoMedicoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoMedicoField, value) != true)) {
                    this.TipoMedicoField = value;
                    this.RaisePropertyChanged("TipoMedico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoMedico", Namespace="http://schemas.datacontract.org/2004/07/ISITP02.Models")]
    [System.SerializableAttribute()]
    public partial class TipoMedico : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Consulta", Namespace="http://schemas.datacontract.org/2004/07/ISITP02.Models")]
    [System.SerializableAttribute()]
    public partial class Consulta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ISI_TP02_Forms.ServiceReference2.Funcionario FuncionarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FuncionárioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ISI_TP02_Forms.ServiceReference2.Hospital HospitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HospitalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ISI_TP02_Forms.ServiceReference2.Medico MedicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MedicoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ISI_TP02_Forms.ServiceReference2.Utente UtenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UtenteIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ISI_TP02_Forms.ServiceReference2.Funcionario Funcionario {
            get {
                return this.FuncionarioField;
            }
            set {
                if ((object.ReferenceEquals(this.FuncionarioField, value) != true)) {
                    this.FuncionarioField = value;
                    this.RaisePropertyChanged("Funcionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FuncionárioId {
            get {
                return this.FuncionárioIdField;
            }
            set {
                if ((this.FuncionárioIdField.Equals(value) != true)) {
                    this.FuncionárioIdField = value;
                    this.RaisePropertyChanged("FuncionárioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ISI_TP02_Forms.ServiceReference2.Hospital Hospital {
            get {
                return this.HospitalField;
            }
            set {
                if ((object.ReferenceEquals(this.HospitalField, value) != true)) {
                    this.HospitalField = value;
                    this.RaisePropertyChanged("Hospital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HospitalId {
            get {
                return this.HospitalIdField;
            }
            set {
                if ((this.HospitalIdField.Equals(value) != true)) {
                    this.HospitalIdField = value;
                    this.RaisePropertyChanged("HospitalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ISI_TP02_Forms.ServiceReference2.Medico Medico {
            get {
                return this.MedicoField;
            }
            set {
                if ((object.ReferenceEquals(this.MedicoField, value) != true)) {
                    this.MedicoField = value;
                    this.RaisePropertyChanged("Medico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MedicoId {
            get {
                return this.MedicoIdField;
            }
            set {
                if ((this.MedicoIdField.Equals(value) != true)) {
                    this.MedicoIdField = value;
                    this.RaisePropertyChanged("MedicoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ISI_TP02_Forms.ServiceReference2.Utente Utente {
            get {
                return this.UtenteField;
            }
            set {
                if ((object.ReferenceEquals(this.UtenteField, value) != true)) {
                    this.UtenteField = value;
                    this.RaisePropertyChanged("Utente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UtenteId {
            get {
                return this.UtenteIdField;
            }
            set {
                if ((this.UtenteIdField.Equals(value) != true)) {
                    this.UtenteIdField = value;
                    this.RaisePropertyChanged("UtenteId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Funcionario", Namespace="http://schemas.datacontract.org/2004/07/ISITP02.Models")]
    [System.SerializableAttribute()]
    public partial class Funcionario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ISI_TP02_Forms.ServiceReference2.Consulta[] ConsultasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataEntradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NIFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ISI_TP02_Forms.ServiceReference2.TipoFuncionario TipoFuncionarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ISI_TP02_Forms.ServiceReference2.Consulta[] Consultas {
            get {
                return this.ConsultasField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsultasField, value) != true)) {
                    this.ConsultasField = value;
                    this.RaisePropertyChanged("Consultas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Contacto {
            get {
                return this.ContactoField;
            }
            set {
                if ((this.ContactoField.Equals(value) != true)) {
                    this.ContactoField = value;
                    this.RaisePropertyChanged("Contacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataEntrada {
            get {
                return this.DataEntradaField;
            }
            set {
                if ((this.DataEntradaField.Equals(value) != true)) {
                    this.DataEntradaField = value;
                    this.RaisePropertyChanged("DataEntrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NIF {
            get {
                return this.NIFField;
            }
            set {
                if ((this.NIFField.Equals(value) != true)) {
                    this.NIFField = value;
                    this.RaisePropertyChanged("NIF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ISI_TP02_Forms.ServiceReference2.TipoFuncionario TipoFuncionario {
            get {
                return this.TipoFuncionarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoFuncionarioField, value) != true)) {
                    this.TipoFuncionarioField = value;
                    this.RaisePropertyChanged("TipoFuncionario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hospital", Namespace="http://schemas.datacontract.org/2004/07/ISITP02.Models")]
    [System.SerializableAttribute()]
    public partial class Hospital : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ISI_TP02_Forms.ServiceReference2.Consulta[] ConsultasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalizacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ISI_TP02_Forms.ServiceReference2.Utente[] UtentesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ISI_TP02_Forms.ServiceReference2.Consulta[] Consultas {
            get {
                return this.ConsultasField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsultasField, value) != true)) {
                    this.ConsultasField = value;
                    this.RaisePropertyChanged("Consultas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localizacao {
            get {
                return this.LocalizacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalizacaoField, value) != true)) {
                    this.LocalizacaoField = value;
                    this.RaisePropertyChanged("Localizacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ISI_TP02_Forms.ServiceReference2.Utente[] Utentes {
            get {
                return this.UtentesField;
            }
            set {
                if ((object.ReferenceEquals(this.UtentesField, value) != true)) {
                    this.UtentesField = value;
                    this.RaisePropertyChanged("Utentes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Utente", Namespace="http://schemas.datacontract.org/2004/07/ISITP02.Models")]
    [System.SerializableAttribute()]
    public partial class Utente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ISI_TP02_Forms.ServiceReference2.Consulta[] ConsultasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataEntradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ISI_TP02_Forms.ServiceReference2.Hospital HospitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NIFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ISI_TP02_Forms.ServiceReference2.TipoUtente TipoUtenteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ISI_TP02_Forms.ServiceReference2.Consulta[] Consultas {
            get {
                return this.ConsultasField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsultasField, value) != true)) {
                    this.ConsultasField = value;
                    this.RaisePropertyChanged("Consultas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataEntrada {
            get {
                return this.DataEntradaField;
            }
            set {
                if ((this.DataEntradaField.Equals(value) != true)) {
                    this.DataEntradaField = value;
                    this.RaisePropertyChanged("DataEntrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ISI_TP02_Forms.ServiceReference2.Hospital Hospital {
            get {
                return this.HospitalField;
            }
            set {
                if ((object.ReferenceEquals(this.HospitalField, value) != true)) {
                    this.HospitalField = value;
                    this.RaisePropertyChanged("Hospital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NIF {
            get {
                return this.NIFField;
            }
            set {
                if ((this.NIFField.Equals(value) != true)) {
                    this.NIFField = value;
                    this.RaisePropertyChanged("NIF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ISI_TP02_Forms.ServiceReference2.TipoUtente TipoUtente {
            get {
                return this.TipoUtenteField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoUtenteField, value) != true)) {
                    this.TipoUtenteField = value;
                    this.RaisePropertyChanged("TipoUtente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoFuncionario", Namespace="http://schemas.datacontract.org/2004/07/ISITP02.Models")]
    [System.SerializableAttribute()]
    public partial class TipoFuncionario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoUtente", Namespace="http://schemas.datacontract.org/2004/07/ISITP02.Models")]
    [System.SerializableAttribute()]
    public partial class TipoUtente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IHospitalService")]
    public interface IHospitalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/CreateMedico", ReplyAction="http://tempuri.org/IHospitalService/CreateMedicoResponse")]
        bool CreateMedico(string nome, int tipoMedicoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/CreateMedico", ReplyAction="http://tempuri.org/IHospitalService/CreateMedicoResponse")]
        System.Threading.Tasks.Task<bool> CreateMedicoAsync(string nome, int tipoMedicoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GetAllMedicos", ReplyAction="http://tempuri.org/IHospitalService/GetAllMedicosResponse")]
        ISI_TP02_Forms.ServiceReference2.Medico[] GetAllMedicos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GetAllMedicos", ReplyAction="http://tempuri.org/IHospitalService/GetAllMedicosResponse")]
        System.Threading.Tasks.Task<ISI_TP02_Forms.ServiceReference2.Medico[]> GetAllMedicosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GetMedicoById", ReplyAction="http://tempuri.org/IHospitalService/GetMedicoByIdResponse")]
        ISI_TP02_Forms.ServiceReference2.Medico GetMedicoById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GetMedicoById", ReplyAction="http://tempuri.org/IHospitalService/GetMedicoByIdResponse")]
        System.Threading.Tasks.Task<ISI_TP02_Forms.ServiceReference2.Medico> GetMedicoByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/UpdateMedico", ReplyAction="http://tempuri.org/IHospitalService/UpdateMedicoResponse")]
        bool UpdateMedico(int id, string nome, int tipoMedicoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/UpdateMedico", ReplyAction="http://tempuri.org/IHospitalService/UpdateMedicoResponse")]
        System.Threading.Tasks.Task<bool> UpdateMedicoAsync(int id, string nome, int tipoMedicoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/DeleteMedico", ReplyAction="http://tempuri.org/IHospitalService/DeleteMedicoResponse")]
        bool DeleteMedico(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/DeleteMedico", ReplyAction="http://tempuri.org/IHospitalService/DeleteMedicoResponse")]
        System.Threading.Tasks.Task<bool> DeleteMedicoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/CreateTipoMedico", ReplyAction="http://tempuri.org/IHospitalService/CreateTipoMedicoResponse")]
        bool CreateTipoMedico(string descricao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/CreateTipoMedico", ReplyAction="http://tempuri.org/IHospitalService/CreateTipoMedicoResponse")]
        System.Threading.Tasks.Task<bool> CreateTipoMedicoAsync(string descricao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/DeleteTipoMedico", ReplyAction="http://tempuri.org/IHospitalService/DeleteTipoMedicoResponse")]
        bool DeleteTipoMedico(string descricao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/DeleteTipoMedico", ReplyAction="http://tempuri.org/IHospitalService/DeleteTipoMedicoResponse")]
        System.Threading.Tasks.Task<bool> DeleteTipoMedicoAsync(string descricao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/CreateHospital", ReplyAction="http://tempuri.org/IHospitalService/CreateHospitalResponse")]
        bool CreateHospital(string nome, string localizacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/CreateHospital", ReplyAction="http://tempuri.org/IHospitalService/CreateHospitalResponse")]
        System.Threading.Tasks.Task<bool> CreateHospitalAsync(string nome, string localizacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GETALLHOSPITAIS", ReplyAction="http://tempuri.org/IHospitalService/GETALLHOSPITAISResponse")]
        ISI_TP02_Forms.ServiceReference2.Hospital[] GETALLHOSPITAIS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GETALLHOSPITAIS", ReplyAction="http://tempuri.org/IHospitalService/GETALLHOSPITAISResponse")]
        System.Threading.Tasks.Task<ISI_TP02_Forms.ServiceReference2.Hospital[]> GETALLHOSPITAISAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GetHospitalByLoc", ReplyAction="http://tempuri.org/IHospitalService/GetHospitalByLocResponse")]
        ISI_TP02_Forms.ServiceReference2.Hospital GetHospitalByLoc(string localização);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GetHospitalByLoc", ReplyAction="http://tempuri.org/IHospitalService/GetHospitalByLocResponse")]
        System.Threading.Tasks.Task<ISI_TP02_Forms.ServiceReference2.Hospital> GetHospitalByLocAsync(string localização);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/AutenticarUtilizador", ReplyAction="http://tempuri.org/IHospitalService/AutenticarUtilizadorResponse")]
        ISI_TP02_Forms.ServiceReference2.Funcionario AutenticarUtilizador(ISI_TP02_Forms.ServiceReference2.Funcionario f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/AutenticarUtilizador", ReplyAction="http://tempuri.org/IHospitalService/AutenticarUtilizadorResponse")]
        System.Threading.Tasks.Task<ISI_TP02_Forms.ServiceReference2.Funcionario> AutenticarUtilizadorAsync(ISI_TP02_Forms.ServiceReference2.Funcionario f);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHospitalServiceChannel : ISI_TP02_Forms.ServiceReference2.IHospitalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HospitalServiceClient : System.ServiceModel.ClientBase<ISI_TP02_Forms.ServiceReference2.IHospitalService>, ISI_TP02_Forms.ServiceReference2.IHospitalService {
        
        public HospitalServiceClient() {
        }
        
        public HospitalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HospitalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HospitalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HospitalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateMedico(string nome, int tipoMedicoId) {
            return base.Channel.CreateMedico(nome, tipoMedicoId);
        }
        
        public System.Threading.Tasks.Task<bool> CreateMedicoAsync(string nome, int tipoMedicoId) {
            return base.Channel.CreateMedicoAsync(nome, tipoMedicoId);
        }
        
        public ISI_TP02_Forms.ServiceReference2.Medico[] GetAllMedicos() {
            return base.Channel.GetAllMedicos();
        }
        
        public System.Threading.Tasks.Task<ISI_TP02_Forms.ServiceReference2.Medico[]> GetAllMedicosAsync() {
            return base.Channel.GetAllMedicosAsync();
        }
        
        public ISI_TP02_Forms.ServiceReference2.Medico GetMedicoById(int id) {
            return base.Channel.GetMedicoById(id);
        }
        
        public System.Threading.Tasks.Task<ISI_TP02_Forms.ServiceReference2.Medico> GetMedicoByIdAsync(int id) {
            return base.Channel.GetMedicoByIdAsync(id);
        }
        
        public bool UpdateMedico(int id, string nome, int tipoMedicoId) {
            return base.Channel.UpdateMedico(id, nome, tipoMedicoId);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateMedicoAsync(int id, string nome, int tipoMedicoId) {
            return base.Channel.UpdateMedicoAsync(id, nome, tipoMedicoId);
        }
        
        public bool DeleteMedico(int id) {
            return base.Channel.DeleteMedico(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteMedicoAsync(int id) {
            return base.Channel.DeleteMedicoAsync(id);
        }
        
        public bool CreateTipoMedico(string descricao) {
            return base.Channel.CreateTipoMedico(descricao);
        }
        
        public System.Threading.Tasks.Task<bool> CreateTipoMedicoAsync(string descricao) {
            return base.Channel.CreateTipoMedicoAsync(descricao);
        }
        
        public bool DeleteTipoMedico(string descricao) {
            return base.Channel.DeleteTipoMedico(descricao);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteTipoMedicoAsync(string descricao) {
            return base.Channel.DeleteTipoMedicoAsync(descricao);
        }
        
        public bool CreateHospital(string nome, string localizacao) {
            return base.Channel.CreateHospital(nome, localizacao);
        }
        
        public System.Threading.Tasks.Task<bool> CreateHospitalAsync(string nome, string localizacao) {
            return base.Channel.CreateHospitalAsync(nome, localizacao);
        }
        
        public ISI_TP02_Forms.ServiceReference2.Hospital[] GETALLHOSPITAIS() {
            return base.Channel.GETALLHOSPITAIS();
        }
        
        public System.Threading.Tasks.Task<ISI_TP02_Forms.ServiceReference2.Hospital[]> GETALLHOSPITAISAsync() {
            return base.Channel.GETALLHOSPITAISAsync();
        }
        
        public ISI_TP02_Forms.ServiceReference2.Hospital GetHospitalByLoc(string localização) {
            return base.Channel.GetHospitalByLoc(localização);
        }
        
        public System.Threading.Tasks.Task<ISI_TP02_Forms.ServiceReference2.Hospital> GetHospitalByLocAsync(string localização) {
            return base.Channel.GetHospitalByLocAsync(localização);
        }
        
        public ISI_TP02_Forms.ServiceReference2.Funcionario AutenticarUtilizador(ISI_TP02_Forms.ServiceReference2.Funcionario f) {
            return base.Channel.AutenticarUtilizador(f);
        }
        
        public System.Threading.Tasks.Task<ISI_TP02_Forms.ServiceReference2.Funcionario> AutenticarUtilizadorAsync(ISI_TP02_Forms.ServiceReference2.Funcionario f) {
            return base.Channel.AutenticarUtilizadorAsync(f);
        }
    }
}
